#BlockCmdPerVer configuration

#Version of the config, used to update old configs. Please do not change this option.
version: 1

#Set this to false to disable the plugin
enabled: true 

#Blocked commands per version. Put the commands you want to block per version in the version's brackets.
#Example: If you want to block the /summon and /give commands on 1.7, make the 1.7 line be this:
#1.7: ["summon", "give]
#Do not forget the quotes.
#The versions include all subversions (Ex: the 1.12 option also includes 1.12.1 and 1.12.2)
1.4: []
1.5: []
1.6: []
1.7: []
1.8: []
1.9: []
1.10: []
1.11: []
1.12: []
1.13: []
1.14: []
1.15: []
1.16: []